### ISSUE TITLE
@conda-forge-admin, please add user conda-forge/jupyter-book

### ISSUE THREAD

**Issue by agoose77** [conda-forge/sphinx-remove-toctrees-feedstock#1]

**Comment by maresb** [comment]
Can teams be added? Shall I add the 3 individuals?

**Comment by agoose77** [comment]
Thanks for the quick appearance! We're just getting up to speed with project organisation, and we want to have the jupyter-book repo on each feedstock so that we have a central point at which new contributors can be added.

You can use one feedstock as _another_ feedstock "user", which acts like inheritance. In future, we'll likely create a meta-recipe for this, but for now we can just use `jupyter-book`.

**Comment by agoose77** [comment]
Thanks for the quick appearance! We're just getting up to speed with project organisation, and we want to have the jupyter-book repo on each feedstock so that we have a central point at which new contributors can be added.

You can use one feedstock as _another_ feedstock "user", which acts like inheritance. In future, we'll likely create a meta-recipe for this, but for now we can just use `jupyter-book`.

I opened this issue among several others using a program, but made a typo :facepalm:. The other open issue should hopefully trigger the conda-forge machinery.

**Comment by maresb** [comment]
Seems to have been a misunderstanding. Ref: https://github.com/conda-forge/jupyter-book-feedstock/pull/19#issuecomment-1456500310

**Comment by agoose77** [comment]
@maresb yes, indeed. Thanks for your patience!

**Comment by maresb** [comment]
No worries, and thanks for your enthusiasm!
